spring:
  application:
    name: inditex-product-api
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration/common
    baseline-on-migrate: true
    clean-disabled: false
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, mappings, env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

security:
  jwt:
    secret: this-is-at-least-32-bytes-long-please-change
    expiration-ms: 60000
app:
  security:
    allowed-origins:
      - http://localhost:8080
    whitelisted-paths:
      - /actuator
      - /inditex/api/v1/auth/login
      - /inditex/api/v1/**
info:
  app:
    name: Get product price API
    description: Workation sorting service
    version: 1.0.0

