springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
spring:
  flyway:
    clean-disabled: true
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info

app:
  security:
    allowed-origins:
      - http://localhost:8080
    whitelisted-paths:
      - /actuator
      - /inditex/api/v1/auth/login
